build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"
    run_tests:
        image: python:2-alpine
        commands:
            - pip install -r requirements.txt
            - python testing.py

publish:
    docker:
        repo: kaztakada/cicd_demoapp
        tag: latest
        username: kaztakada
        password: SR20dett1
        email: ktakada@cisco.com 

deploy:
    webhook:
        image: plugins/drone-webhook
        skip_verify: true
        method: POST
        auth:
            username: CICD1
            password: CICD1
        urls:
            - https://control.sandbox.imapex.io/marathon/v2/apps/class/kaztakada/restart?force=true

notify:
    spark:
        image: hpreston/drone-spark
        auth_token: MjIyMjU5MDItZjE0Ni00MzljLWFmMTMtMmY0YTg2NDRiMmE1MDEwMTQ0YzUtYTY4
        roomId: Y2lzY29zcGFyazovL3VzL1JPT00vYTNhNjA4YjAtZjQyYS0xMWU2LWEwMDItMWY2MWUxNDU5ZTcy
